### ISSUE TITLE
DateTimeField Default Now throws error

### ISSUE THREAD

**Issue by nickmitchko** [caretdev/django-iris#2]
Model defined like so: 
```python
migrations.AddField(
    model_name='user',
    name='activity_at',
    field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last completion activity'),
)
```

Throws an error when using `django.utils.timezone.now`

```batch
PS C:\Users\nmitchko\Documents\Sales\Projects\label-studio-iris\label-studio> .\test.bat
Current platform is win32, apply sqlite fix
Can't load sqlite3.dll from current directory
python version: 3 sqlite minor version: 9

=> Database and media directory: C:\Users\nmitchko\AppData\Local\label-studio\label-studio
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 45850
Initializing database..
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\nmitchko\Documents\Sales\Projects\label-studio-iris\label-studio\label_studio\server.py", line 399, in <module>
    sys.exit(main())
  File "C:\Users\nmitchko\Documents\Sales\Projects\label-studio-iris\label-studio\label_studio\server.py", line 283, in main
    _apply_database_migrations()
  File "C:\Users\nmitchko\Documents\Sales\Projects\label-studio-iris\label-studio\label_studio\server.py", line 59, in _apply_database_migrations
    call_command('migrate', '--no-color', verbosity=0)
  File "C:\Python39\lib\site-packages\django\core\management\__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
[%msg: < LITERAL ('DEFAULT') expected, ? found^ALTER TABLE "htx_user" ADD COLUMN "activity_at" TIMESTAMP DEFAULT ?>]
PS C:\Users\nmitchko\Documents\Sales\Projects\label-studio-iris\label-studio>
```

**Comment by nickmitchko** [comment]
This issue actually happens for any django migration resulting in SQL of syntax
`Alter Table <table> ADD COLUMN <col>`

**Comment by daimor** [comment]
Could you check it?
the issue is in `DEFAULT ?` where the engine does not expect to see parameter

**Comment by daimor** [comment]
0.1.7.b1 version is available for testing

**Comment by nickmitchko** [comment]
@daimor The issue is actually in the IRIS SQL execution. You can reproduce the error using the class below. If we can intercept that DEFAULT ? it'll be a quick fix on the python side. Regardless, I've filed a JIRA to fix the behavior that SQL execution cannot prepare `ALTER TABLE <table> ADD COLUMN <col> <type> DEFAULT ?` without an error.

```java
Class User.test
{

/// Description
ClassMethod ALTERTEST() As %Status
{
    Set sc = $$$OK
    Set qAlter = "ALTER TABLE N ADD COLUMN place VARCHAR(255) DEFAULT ?"
    // Create Table
    
    &sql(CREATE TABLE N(NAME VARCHAR(10)))
    Write "1. CREATE TABLE N(NAME VARCHAR(10)) -- ", SQLCODE, !

    // Alter Table
    Set alterSQL = ##class(%SQL.Statement).%New()
    Set sc = alterSQL.%Prepare(qAlter)
    Write "2. %Prepare(", qAlter, ") -- " ,!,!,  sc, !, !
    IF $$$ISERR(sc){
        Write "Failed Preparation"
        &sql(DROP TABLE N)
    } ELSE {
        Set sc = alterSQL.%Execute("NOW()")
    }

    Return sc
}

}

```

**Comment by nickmitchko** [comment]
Looking at the latest, commit, I think you've fixed the issue. Regardless, I'll work to get the SQL team to evaluate the change in the long term
